from __future__ import annotations

import random

DAD_JOKES = [
    "Why don't skeletons fight each other? They don't have the guts.",
    "I used to play piano by ear, but now I use my hands.",
    "Why don't scientists trust atoms? Because they make up everything.",
    "I'm reading a book about anti-gravity. It's impossible to put down.",
    "Did you hear about the claustrophobic astronaut? He just needed a little space.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "I only know 25 letters of the alphabet. I don't know y.",
    "What do you call fake spaghetti? An impasta.",
    "How does a penguin build its house? Igloos it together.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "I'm on a seafood diet. I see food and I eat it.",
    "Why can't you give Elsa a balloon? Because she will let it go.",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "I invented a new word: plagiarism.",
    "Did you hear about the guy who invented Lifesavers? They say he made a mint.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What do you call a fish with no eyes? A fsh.",
    "How do you organize a space party? You planet.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "What's orange and sounds like a parrot? A carrot.",
    "I would tell you a chemistry joke, but I know I wouldn't get a reaction.",
    "Why was six afraid of seven? Because seven eight nine.",
    "What did one wall say to the other wall? I'll meet you at the corner.",
    "How does the moon cut his hair? Eclipse it.",
    "What do you call a can opener that doesn't work? A can't opener.",
    "Why did the coffee file a police report? It got mugged.",
    "What's brown and sticky? A stick.",
    "I used to be a banker, but I lost interest.",
    "Why did the math book look sad? Because it had too many problems.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why don't oysters donate to charity? Because they're shellfish.",
    "I'm afraid for the calendar. Its days are numbered.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
    "Why did the picture go to jail? Because it was framed.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "How do you make a tissue dance? You put a little boogie in it.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call a factory that makes okay products? A satisfactory.",
    "I used to hate facial hair, but then it grew on me.",
    "Why do bees have sticky hair? Because they use a honeycomb.",
    "I'm reading a horror story in braille. Something bad is about to happen, I can feel it.",
    "Why did the stadium get hot after the game? All of the fans left.",
    "What do you call a fly without wings? A walk.",
    "What's the best time to go to the dentist? Tooth-hurty.",
    "Why don't scientists trust stairs? Because they're always up to something.",
    "I have a fear of speed bumps, but I'm slowly getting over it.",
    "Did you hear the rumor about butter? Well, I'm not going to spread it.",
    "Why did the man put his money in the freezer? He wanted cold, hard cash.",
    "What do you call an alligator in a vest? An investigator.",
    "Why did the invisible man turn down the job offer? He couldn't see himself doing it.",
    "What do you call a pig that does karate? A pork chop.",
    "Why did the belt get arrested? For holding up a pair of pants.",
    "What do you call a sad cup of coffee? A depresso.",
    "I was going to look for my missing watch, but I could never find the time.",
    "What do you call a group of disorganized cats? A cat-astrophe.",
    "Why did the man run laps around his bed? Because he was trying to catch up on his sleep.",
    "What do you call a computer that sings? A Dell.",
    "Why did the smartphone need glasses? It lost all its contacts.",
    "I tried to catch some fog earlier. I mist.",
    "What do you call a dog magician? A labracadabrador.",
    "Why do seagulls fly over the sea? Because if they flew over the bay, they'd be bagels.",
    "What do you call a sleeping bull? A bulldozer.",
    "Why don't melons get married? Because they cantaloupe.",
    "What's the difference between a hippo and a Zippo? One is really heavy, and the other is a little lighter.",
    "Why did the cookie go to the doctor? Because it felt crummy.",
    "What do you get from a pampered cow? Spoiled milk.",
    "I bought the world's worst thesaurus yesterday. Not only is it terrible, it's terrible.",
    "What do you call an elephant that doesn't matter? An irrelephant.",
    "Why can't you trust a balloon? It's full of hot air.",
    "What did the buffalo say to his son when he left for college? Bison.",
    "Why did the man name his dogs Rolex and Timex? They were watch dogs.",
    "Why do we tell actors to break a leg? Because every play has a cast.",
    "What did the drummer call his twin daughters? Anna one, Anna two.",
    "Why did the man put his money in a blender? He wanted to make some liquid assets.",
    "What do you call a dinosaur that crashes his car? Tyrannosaurus wrecks.",
    "Why did the tree go to the dentist? To get a root canal.",
    "What's a pirate's favorite letter? You'd think it's R, but it's the C.",
    "Why did the football coach go to the bank? To get his quarterback.",
    "What do you call cheese by itself? Provolone.",
    "Why did the man get fired from the calendar factory? He took a day off.",
    "What do you call two witches who share a room? Broom-mates.",
    "Why do fish avoid using computers? They're afraid of the net.",
    "Why did the burglar hang up his stocking? He wanted his Christmas haul.",
    "What do you call a cow with no legs? Ground beef.",
    "Why did the man bring a ladder to the bar? He heard the drinks were on the house.",
    "What do you call a bee that can't make up its mind? A maybe.",
    "What do you call a fish wearing a bowtie? So-fish-ticated.",
    "Why did the student eat his homework? Because the teacher said it was a piece of cake.",
    "Why did the orange stop rolling down the hill? It ran out of juice.",
    "What do you call a very happy cowboy? A jolly rancher.",
    "Why did the scientist install a knocker on his door? He wanted to win the No-bell prize.",
    "What do you call a lazy kangaroo? A pouch potato.",
    "Why did the gym close down? It just didn't work out.",
    "What do you call a bear caught in the rain? A drizzly bear.",
    "What do you call an old snowman? Water.",
    "What's the loudest pet you can get? A trumpet.",
    "Why did the baker stop making donuts? He was tired of the hole business.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "Why did the man get a ladder for his printer? Because he wanted to see it upgrade.",
    "What do you call a parade of rabbits hopping backward? A receding hare-line.",
    "Why did the man put a clock under his desk? He wanted to work overtime.",
    "Why did the computer keep freezing? It left its Windows open.",
    "What do you call a droid that takes the long way around? R2-Detour.",
    "What do you call a can that crushes itself? A self-esteem.",
    "Why don't skeletons ever go trick-or-treating? Because they have no body to go with.",
    "What do you call a nervous javelin thrower? Shakespeare.",
    "Why did the man stare at the orange juice carton? Because it said concentrate.",
    "What kind of tree fits in your hand? A palm tree.",
    "Why did the astronaut break up with his girlfriend? He needed space.",
    "What did one plate say to the other plate? Dinner is on me.",
    "What do you call a group of musical whales? An orca-stra.",
    "What did the grape do when it got stepped on? It let out a little wine.",
    "What's a vampire's favorite fruit? A blood orange.",
    "What do you call a duck that gets all A's? A wise quacker.",
    "Why do cows wear bells? Because their horns don't work.",
    "Why did the man bring string to the party? So he could tie one on.",
    "What did the fisherman say to the magician? Pick a cod, any cod.",
    "Why don't programmers like nature? It has too many bugs.",
    "What do you call a computer floating in the ocean? A screensaver.",
    "Why did the man take a pencil to bed? To draw the curtains.",
    "What's the best way to watch a fly fishing tournament? Live stream.",
    "Why did the man quit his job at the shoe factory? He just didn't fit in.",
    "What do you call a pile of cats? A meowntain.",
    "Why did the baker go broke? He kneaded the dough but couldn't rise to the occasion.",
    "What do you call a sleepy dinosaur? A dino-snore.",
    "What do you call a fish that needs help with vocals? Auto-tuna.",
    "Why did the man bring a ruler to bed? He wanted to see how long he slept.",
    "What do you call an owl who does magic tricks? Hoo-dini.",
    "Why did the light bulb fail school? It wasn't that bright.",
    "What do you call a pony with a cough? A little horse.",
    "Why did the frog take the bus to work? His car got toad.",
    "What do you call a cow during an earthquake? A milkshake.",
    "Why did the man stop telling silent jokes? No one was getting them.",
    "What do you call a rabbit that tells good jokes? A funny bunny.",
    "Why did the man's watch break at the gym? It ran out of time.",
    "What's a math teacher's favorite season? Sum-mer.",
    "Why don't sharks attack lawyers? Professional courtesy.",
    "What's a ghost's favorite dessert? I-scream.",
    "Why did the man refuse to play cards in the jungle? Too many cheetahs.",
    "What do you call a fake stone? A shamrock.",
    "Why did the man get in trouble at the bakery? He was caught loafing around.",
    "What did the tie say to the hat? You go on ahead, I'll hang around.",
    "Why don't ants get sick? They have tiny anty-bodies.",
    "Why did the man take a ladder to school? He wanted to go to high school.",
    "What do you call a suspicious burrito? A questionable-a.",
    "Why was the broom late? It over-swept.",
    "Why did the man wear sunglasses inside? Because his friends said he was too bright.",
    "What do you call a cold dog? A chili dog.",
    "Why did the man's garden grow so well? He had a green thumb and a lot of thyme.",
    "What do you call a nosy pepper? Jalapeno business.",
    "Why did the man's alarm clock get promoted? It was always alarming everyone about being on time.",
    "What do you call a fruit that's always right? A wise-melon.",
    "Why did the man throw a clock out the window? He wanted to see time fly.",
    "What do you call a boat that doesn't move? A stationary boat -- also known as a dock.",
    "Why did the baker's hands hurt? He kneaded a break.",
    "What do you call a dog with no legs? Doesn't matter, he still won't come.",
    "Why did the pony get sent to its room? It kept horsing around.",
    "What do you call an angry pea? Grump-pea.",
    "Why did the man buy a dictionary? He wanted to expand his vocabulary at all cost-s.",
    "What do you call a sad strawberry? A blueberry.",
    "Why did the barber win the race? He knew a shortcut.",
    "What do you call a group of eight hobbits? A hobbyte.",
    "Why did the man refuse to fight the clock? Because time waits for no one.",
    "What do you call a well-balanced horse? Stable.",
    "Why did the man stop reading books on anti-gravity? He couldn't put them down.",
    "What do you call a fish that's a great singer? Elvis Parsley.",
    "Why did the man bring his ladder to church? He wanted to reach the higher power.",
    "What do you call a happy mushroom? A fungi to be around.",
    "Why did the man get a job at the orange juice factory? He wanted to make some pulp fiction.",
    "What do you call a pig with no manners? A boar.",
    "Why did the man's boss ask him to leave the calendar company? He took too many days off.",
    "What do you call a lizard that tells jokes? A stand-up chameleon.",
    "Why did the man get a parking ticket at the gym? He was caught doing donuts.",
    "What do you call a fish that wears a crown? King mackerel.",
    "Why did the man refuse to eat the clock? It was too time-consuming.",
    "What do you call a snowman in July? A puddle.",
    "Why did the man's plants keep dying? He kept telling them bad soil puns.",
    "What do you call a cat that likes to bowl? An alley cat.",
    "Why did the man's car break down at the bakery? It ran out of dough.",
    "What do you call a bear with no ears? B.",
    "Why did the man's shirt get promoted? It was outstanding in the field.",
    "What do you call a magician's dog? A labracadabrador -- taken, so instead: A trick pup.",
    "Why did the man carry a broken clock around town? He wanted to give people the right time twice a day.",
    "What do you call a nervous dog? A shaky-canine.",
    "Why did the man's spreadsheet break up with him? It couldn't handle the relationship-s.",
    "What do you call a fish that does magic tricks? An electric eel.",
    "Why did the man refuse dessert at the bakery? He was on a roll already.",
    "What do you call a factory worker who makes lasers? A laser-focused employee.",
    "Why did the man's toaster get anxious? It kept popping under pressure.",
    "What do you call a pile of kittens? A meow-tain range.",
    "Why did the man plant a light bulb? He wanted to grow a power plant.",
    "What do you call a fish with a cold? A snifish.",
    "Why did the man's spreadsheet go to therapy? Too many unresolved formulas.",
    "What do you call a group of chess players bragging in a hotel lobby? Chess nuts boasting in an open foyer.",
    "Why did the man's phone go to school? To improve its cell-f esteem.",
    "What do you call a bear stuck in the rain with no umbrella? Wet.",
]


def random_dad_joke() -> str:
    return random.choice(DAD_JOKES)
